version: '3.3'
services:
  app:
    container_name: backend
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      DATABASE_NAME: categories
      DATABASE_URI: mongodb://admin:admin@database:27017/
    ports:
      - '3000:3000'
    depends_on:
      - database
  database:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin